### ISSUE TITLE
Configuration option for requiring phone/email

### ISSUE THREAD

**Issue by jashort** [kumoregdev/kumoreg#3]
Add configuration option to make phone/email optional
- Should allow saving attendees without phone/email (used for mini events)
- Basically, enable/disable validation for those fields
- Configure in application.properties
- Should apply to all attendees

**Comment by micahcowan** [comment]
I could take this if you haven't started in on it already.

**Comment by jashort** [comment]
Feel free!

**Comment by micahcowan** [comment]
Heh, this should be pretty easy, but I seem to be a tad stuck on implementation approach. I see I can use the `@Value` annotation (as used for the print-enabling option) to set a variable according to what's in the config file, or the more sweeping variable-name-based approach of using `@ConfigurationProperties` on a class to load up a batch of options. Neither of those seem like a good idea in the Attendee model, where I assume any additional properties will alter the model in the database (unless there's an attribute to exempt a property? Don't know Vaadin that well yet (or Spring Boot for that matter)).

There also looks like there's a more direct way to access the properties from the ApplicationContext, but I'm not sure of the right way to hand over that context to the model, either (it's not available via some class method I assume?).

Maybe a separate "Config" class with @ConfigurationProperties(prefix = "kumoreg")? Seems overkill for when we have a total of two options, maybe.

**Comment by jashort** [comment]
You are correct, there are lots of ways to do this. 

1) If you annotate a variable @Transient in the model, it won't get added to the database. So something like this would probably do it (disclaimer, I haven't actually tested it, and don't actually use the name below for the property :) ): 

    ```
    @Transient
    @Value("${kumoreg.validateEveryDarnThingEver}")
    private Boolen validateEverything;
    ```
2) Another way to do it would be to re-factor the validation out of the Attendee class and put it somewhere else. A static class called AttendeeService would tend to make sense. Then instead of calling ```attendee.validate()```, you would call ```AttendeeService.validate(attendee);```

Of the two, I would lean towards option 2 because it makes the Attendee object smaller, and arguably validation that depends on business rules (basically what this is) doesn't belong in the model. It would also make more sense to add things like logging to a Service class than to try to put it in the Model class.

_(Which may raise the question "why is validate in the model to start with?" Like so many things, 1) things got more complicated and 2) it made sense at the time.)_

One thing that may not be obvious about the @Service annotation: it creates beans as a singleton by default - so you don't want to keep any state in the service object (without planning for it and/or using @Scope, anyway).
