### ISSUE TITLE
Allow MMDDYYYY format without slashes in birth date field

### ISSUE THREAD

**Issue by jashort** [kumoregdev/kumoreg#38]
In the birth date field, allow users to enter MMDDYYYY without the slashes or dashes as well.

This should be doable by changing handleUnparsableDateString() in FieldFactory.java

**Comment by micahcowan** [comment]
Alternatively, perhaps the field could auto-insert slashes?

You'll want to take care to avoid issues with single-digit months or days - avoiding slashes means they must include leading zeroes I think.

**Comment by jashort** [comment]
Yeah, definitely. Leading zeroes or slashes are a must - not going to try to guess the difference between 1/11/1990 and 11/1/1990.
