### ISSUE TITLE
Make it easier to add printers

### ISSUE THREAD

**Issue by jashort** [kumoregdev/kumoreg#44]
Currently, adding printers is a pain. Figure out some way to make it better.

- When adding a Computer/printer mapping, default to the current computer's IP address? Would save some typing that way, and the IP address is already displayed.
- Adding printers in CUPS was a real pain because of selecting the drivers in the list of 10,000 different models of HP printer. Maybe add them via a shell script? Could have a script for each printer model. Something like `addprinter officejet 10.11.12.13` and `addprinter laserjet 10.11.12.14`. 
    - If doing that, set the default paper size to Statement (8.5" x 5.5"). At lite, used the driver/filter "HP Officejet Pro 8610, hpcups 3.16.7" with media size "Statement 5.5x8.5in" and set to Portrait. It worked flawlessly.
    - Also, set the printer's name to its IP address. (Could be anything, but just using the IP address seemed to work well)

For what it's worth, in my notes for things learned at Lite, "Adding printers sucks" appears twice.

**Comment by micahcowan** [comment]
I deal with modifying OSS a lot of the time, so modifying CUPS to have like a "default selected" printer driver of our choosing or something would be nice.

But the "addprinter" shell command may be the better idea. Whatever the solution, it'd be nice to also provide admins with the ability to do it from the kumoreg app, letting the server run whatever appropriate commands. Perhaps even combining with the "add printer mapping for this computer" step?

**Comment by micahcowan** [comment]
While we're at it, another "nice-to-have" feature (if a small one)... since the printers are typically all on the same class C IP subnet, it'd be nice to have the printer IP entry auto-fill the first three of the address quad (e.g., "10.0.60."), to save typing and reduce possibility of error. Could possibly just guess this from existing printer IPs, or just look at the latest-entered IP.

**Comment by micahcowan** [comment]
Probably, entering the offset for the badge printing shouldn't be part of the process of adding a new printer, but of later editing existing ones, assuming those two processes diverge more in the future.

**Comment by jashort** [comment]
I was just looking at [Cups4j](http://www.cups4j.org/index.php?option=com_content&view=article&id=4&Itemid=2) and it mentions that it can add printers. Looks like it hasn't been updated in a while, but I'm not sure if that means "abandoned" or "done", but it would be worth knocking out a quick test program to see if it works with Java 8 and whatever the modern version of CUPS is.

Right now KumoReg is just using Java's built in methods for printing - not sure it's worth changing how things print, but adding printers from inside KumoReg would be great.

Re: setting the offset, I think it could just default to zero.

**Comment by jashort** [comment]
Partially fixed in f2500f9e65ee6f2d0cd52c5682d212e9d17322f3 - set useful defaults when creating the computer/printer mapping.
It looks like adding printers isn't actually done in Cups4j yet - looking at just writing a shell script to add printers.
