### ISSUE TITLE
View/Edit Attendee Info from "Check In By Badge" Report

### ISSUE THREAD

**Issue by micahcowan** [kumoregdev/kumoreg#50]
Kim asked for this feature. She'd like it if you can edit/view attendee info by clicking the name from the "Check In By Badge" report, same as if you'd clicked them from the Pre-Reg Checkin or Attendee Search, as this may be the easiest way to find certain kinds of attendees (press and the like, maybe?)

**Comment by jashort** [comment]
Fixed in 7e1a9016d5c527491641359f06d461d7e1d6ac92

Search module needs refactoring, but feature is working.

**Comment by micahcowan** [comment]
This seems to be re-broken as of c2a08d83 - or at least that's where calls to .addItemClickListener() appear to have been removed. It looks like there may have been an accidental code regression in that area (a bunch of minimum sizes had been added for that table/grid, and then removed again in c2a08d83).
