### ISSUE TITLE
Printer scale adjustments, in addition to offsets.

### ISSUE THREAD

**Issue by micahcowan** [kumoregdev/kumoreg#54]
When I've encountered discrepancies between what I ask for, and what I get, in printers, often scaling can also be an issue as well. In the code for pull request #52 (proposed fix for #43), a transformation matrix is established, so it would be quite easy to use new `xScale` and `yScale` values, to complement `xOffset` and `yOffset`, in per-client (or, if #53 is approved, per-printer) settings.

**Comment by jashort** [comment]
I haven't run in to a situation where scaling the whole badge would fix an alignment issue, but I can see where it would be useful to have that configurable just in case.

**Comment by micahcowan** [comment]
Yeah. My memory is mainly of full-page printing on old inkjets, where maybe it chose to scale the whole page down slightly in order to leave the unprintable margins alone. Shouldn't impact lasers, and ideally wouldn't affect any modern printer... but who knows. Better safe than sorry. I'm drawing the line at rotation, though. ;)

Should be trivial, though it'd involve a minor enhancement to the current DB schema.

**Comment by jashort** [comment]
Putting this on the back burner for now
