### ISSUE TITLE
Prevent tab-switching focus to background elements of page

### ISSUE THREAD

**Issue by micahcowan** [kumoregdev/kumoreg#55]
This was discovered to be an issue at Kumo Lite, resulting in client-local app crashes. The problem isn't with our code, and should rightly be categorized a Spring Boot issue... but that doesn't change the fact that it makes for poor UX, and the fact is that we can probably do something about it. Spring Boot is OSS, so we have the opportunity to either fix it there (or in a local/custom copy until our fix is accepted); or if it came to it we could pass our page outputs through a proxy object that applies fixes to do what we need it to.

Anyway, it seems worthwhile to be tracking the issue here, even if it's not technically our issue.

**Comment by jashort** [comment]
Technically a Vaadin thing, not a Spring Boot thing. Still a thing.

Could possibly set a negative tabIndex on all the fields when opening a window, and restore it when the window is closed. [https://vaadin.com/docs/-/part/framework/components/components-features.html](https://vaadin.com/docs/-/part/framework/components/components-features.html)

**Comment by jashort** [comment]
Solved by breaking things out in to separate views instead of using so many popup windows
