### ISSUE TITLE
Import/Export Feature

### ISSUE THREAD

**Issue by jashort** [kumoregdev/kumoreg#6]
Currently, if you set up users, badges, etc ahead of time, you have to do a database dump to move that to another server. While this isn't terrible, it would be handy to have an "Export" button that would dump everything to a file that could be imported in to a clean install with an "Import" button.
- Import / export should have their own roles (and be pretty locked down)
- Only allow import on an empty system (just the initial admin user)
- Export should contain the date of export and software version number, presumably near the top
- Export should probably be in JSON or XML, something human readable
- Should throw errors and abort on bad input (different fields, etc)
- Should work without changing the import/export classes if/when the model classes change

**Comment by micahcowan** [comment]
While it's not quite as human-friendly, I do like CSV for the more efficient format (both JSON or XML will repeat the name of the column, for each field, in each row, which is fairly inefficient - unless of course you use an array in JSON, but then you might as well be using CSV at that point).

Then again, since our database is always relatively small, dunno how much that really matters. :)

**Comment by jashort** [comment]
The flip side, though, is that I'd kind of like to have everything in a single file. Multiple different tables in one CSV file seems...icky. :) 
But yeah, XML gets ridiculous. JSON too, for that matter.

**Comment by jashort** [comment]
Another thought: export/import to a bunch of individual CSV files bundled up in a .zip or .tgz file. Use a separate file for each item type. One downside is that some things that genuinely involve multiple tables (like badges / ageranges / badges_ageranges) would either have to be split up, or would have to get crammed together in to a single really long line)

**Comment by micahcowan** [comment]
Yeah, the more you talk about it, the more I think CSV is a bad idea. Particularly when efficiency isn't a genuine concern of ours, and isn't likely to be (not to mention we could just compress the sucker if we had to and eliminate most of the efficiency concerns - lots of repetition means lots of compressibility :) )

**Comment by jashort** [comment]
Dropping this for now. It's one of those "kind of useful but there are a lot of other ways to do it" things, and SQL dumps have been working fine for backups.
