### ISSUE TITLE
Proper Debian packaging for app installation

### ISSUE THREAD

**Issue by micahcowan** [kumoregdev/kumoreg#78]
This is something you (Jason) brought up during the con: that a lot of the installation script properly belongs in Debian packaging and whatnot, rather than as an install script. I pointed out that packaging Debians is pretty much what I do for my paying job ^_^

Of course, doing this only makes sense if we're pretty sure we're going to stick to Debian, Ubuntu or the like moving forward for our servers. Otherwise we should consider packaging it as a redhat instead, or else just leaving things as they are.

**Comment by jashort** [comment]
Other than hating switching between them, I have no strong feelings on distros, so using Ubuntu/Debian on the server is fine with me.
A couple thoughts:
- It should be generated as part of the build process
Fortunately there are a couple different Maven plugins that would do it. (Basically, `mvn package` should give me a file ready to `dpkg -i` on a server)
- It should install dependencies if they're not there (Java, MySQL, Cups, Cups drivers)
- Ideally, it should set up the database if it doesn't exist. No idea if this is easily possible
- Generating database users and passwords and setting them appropriately in the config file would be cool
- Upgrading via the package manager should not wipe out the existing config files and database

**Comment by micahcowan** [comment]
I figure dependencies should be declared in the packaging, rather than explicitly installed, and then apt could be used to figure out what was missing and install them.

**Comment by jashort** [comment]
Sounds good, just as long as it happens. :)
