### ISSUE TITLE
Refactor presenters creating windows in org.kumoricon.site.attendee.*

### ISSUE THREAD

**Issue by jashort** [kumoregdev/kumoreg#9]
There are a couple places in the org.kumoricon.site.attendee package where Window objects are created by the presenter and displayed. That should be refactored so that the view handles creating new windows itself.

For example, in PreRegPresenter.java:
```
...
            } else {
                warningWindow = new BadgeWarningWindow(this, attendee);
                view.showWindow(warningWindow);
            }
...
```

Should be more like:
```
...
            } else {
                view.showBadgeWarningWindow(this, attendee);
            }
...
``` 

showBadgeWarningWindow will have to be implemented in the view. The same thing applies to the other presenters in .site.attendee.

This is more of a code cleanup todo than an actual bug, since it currently works fine but it's poorly organized.

**Comment by kentpmckinney** [comment]
Please assign this to me.
